apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.22.0 (HEAD)
  labels:
    io.kompose.service: normas
  name: normas
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: normas
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.22.0 (HEAD)
      labels:
        io.kompose.service: normas
    spec:
      containers:
        - env:
            - name: NORMA_API_DB_HOST
              value: jdbc:postgresql://postgres
            - name: NORMA_API_DB_PASSWORD
              value: admin
            - name: NORMA_API_DB_PORT
              value: "5432"
            - name: NORMA_API_DB_USERNAME
              value: admin
            - name: NORMA_API_EXTERNA
              value: http://192.168.68.116:3000/normas
            - name: NORMA_API_PORT
              value: "8080"
          image: sigo/normas-api
          imagePullPolicy: Never
          name: normas
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
