apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.22.0 (HEAD)
  labels:
    io.kompose.service: pgadmin4
  name: pgadmin4
spec:
  ports:
    - name: "15432"
      port: 15432
      targetPort: 80
  selector:
    io.kompose.service: pgadmin4
status:
  loadBalancer: {}
