apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.22.0 (HEAD)
  labels:
    io.kompose.service: pgadmin4
  name: pgadmin4
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pgadmin4
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.22.0 (HEAD)
      labels:
        io.kompose.service: pgadmin4
    spec:
      containers:
        - env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: pe8542@gmail.com
            - name: PGADMIN_DEFAULT_PASSWORD
              value: admin
          image: dpage/pgadmin4
          name: pgadmin4
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
