---
swagger: "2.0"
info:
  description: '"Repositório de Consultorias e Assessorias REST API"'
  version: 1.0.0
  title: Consultorias e Assessorias REST API
  license:
    name: Apache License Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0"
host: localhost:8080
basePath: /
tags:
- name: consultorias-assessorias-controller
  description: Consultoria Controller
paths:
  /consultorias:
    get:
      tags:
      - consultorias-assessorias-controller
      summary: Retorna todas as consultorias cadastradas
      operationId: allUsingGET
      produces:
      - '*/*'
      parameters: []
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Consultoria'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
    post:
      tags:
      - consultorias-assessorias-controller
      summary: Inclui uma consultoria
      operationId: incluirConsultoriaUsingPOST
      consumes:
      - application/json
      produces:
      - '*/*'
      parameters:
      - in: body
        name: consultoria
        description: consultoria
        required: true
        schema:
          $ref: '#/definitions/Consultoria'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Consultoria'
        "201":
          description: Created
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
  /consultorias/{id}:
    get:
      tags:
      - consultorias-assessorias-controller
      summary: Retorna uma consultoria por Id
      operationId: buscarConsultoriaPorIdUsingGET
      produces:
      - '*/*'
      parameters:
      - name: id
        in: path
        description: id
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Consultoria'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
    put:
      tags:
      - consultorias-assessorias-controller
      summary: Atualiza os dados de uma consultoria
      operationId: atualizarConsultoriaUsingPUT
      consumes:
      - application/json
      produces:
      - '*/*'
      parameters:
      - name: id
        in: path
        description: id
        required: true
        type: integer
        format: int64
      - in: body
        name: consultoriaUpdate
        description: consultoriaUpdate
        required: true
        schema:
          $ref: '#/definitions/Consultoria'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Consultoria'
        "201":
          description: Created
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
    delete:
      tags:
      - consultorias-assessorias-controller
      summary: Exclui uma consultoria previamente cadastrada
      operationId: deleteConsultoriaUsingDELETE
      produces:
      - '*/*'
      parameters:
      - name: id
        in: path
        description: id
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: OK
        "204":
          description: No Content
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
definitions:
  Consultoria:
    type: object
    properties:
      codigo:
        type: string
      descricao:
        type: string
      id:
        type: integer
        format: int64
      status:
        type: string
        enum:
        - CANCELADA
        - EM_VIGOR
    title: Consultoria
