---
swagger: "2.0"
info:
  description: '"Repositório de Normas REST API"'
  version: 1.0.0
  title: Normas REST API
  license:
    name: Apache License Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0"
host: localhost:8080
basePath: /
tags:
- name: norma-controller
  description: Norma Controller
paths:
  /normas:
    get:
      tags:
      - norma-controller
      summary: Retorna todas as normas cadastradas
      operationId: allUsingGET
      produces:
      - '*/*'
      parameters: []
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Norma'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
    post:
      tags:
      - norma-controller
      summary: Inclui uma norma
      operationId: incluirNormaUsingPOST
      consumes:
      - application/json
      produces:
      - '*/*'
      parameters:
      - in: body
        name: norma
        description: norma
        required: true
        schema:
          $ref: '#/definitions/Norma'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Norma'
        "201":
          description: Created
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
  /normas/{id}:
    get:
      tags:
      - norma-controller
      summary: Retorna uma norma por Id
      operationId: buscarNormaPorIdUsingGET
      produces:
      - '*/*'
      parameters:
      - name: id
        in: path
        description: id
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Norma'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
    put:
      tags:
      - norma-controller
      summary: Atualiza os dados de uma norma
      operationId: atualizarNormaUsingPUT
      consumes:
      - application/json
      produces:
      - '*/*'
      parameters:
      - name: id
        in: path
        description: id
        required: true
        type: integer
        format: int64
      - in: body
        name: normaUpdate
        description: normaUpdate
        required: true
        schema:
          $ref: '#/definitions/Norma'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Norma'
        "201":
          description: Created
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
    delete:
      tags:
      - norma-controller
      summary: Exclui uma norma previamente cadastrada
      operationId: deleteNormaUsingDELETE
      produces:
      - '*/*'
      parameters:
      - name: id
        in: path
        description: id
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: OK
        "204":
          description: No Content
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
definitions:
  Norma:
    type: object
    properties:
      codigo:
        type: string
      descricao:
        type: string
      id:
        type: integer
        format: int64
      status:
        type: string
        enum:
        - CANCELADA
        - EM_VIGOR
    title: Norma
